version: '3.4'

services:
  gamerentalinvillia:
    image: ${DOCKER_REGISTRY-}gamerentalinvillia
    build:
      context: .
      dockerfile: GameRentalInvillia/Dockerfile
    depends_on:
           - db
  db:
     image: "mcr.microsoft.com/mssql/server"
     environment:
         SA_PASSWORD: "invillia123"
         ACCEPT_EULA: "Y"
     ports:
      - "5433:1433"